#!/usr/bin/env bash
# build-arc-commands.sh — auto-generate /arc-<slug> configs and slash commands.
#
# For each ~/.claude/projects/-home-${USER}/memory/project_<slug>.md that has
# a matching ~/ai/global-graph/projects/<slug-dashed>.md, generate:
#   - ~/.claude/state/arcs/<slug>.conf      (arc-bootstrap.sh input)
#   - ~/.claude/commands/arc-<slug>.md      (slash command)
#
# Idempotent: existing files are NOT overwritten (skipped with note) unless --force.
# This script is the discovery layer; the actual file lists are seeded with
# sensible defaults (project file + global-graph wiki + companion docs found
# under ~/ai/<slug>/docs/ if that directory exists).
#
# Usage:
#   build-arc-commands.sh            # dry-run; lists what WOULD be generated
#   build-arc-commands.sh --apply    # actually write files (skip existing)
#   build-arc-commands.sh --force    # overwrite existing
#
# After generating, manually curate ~/.claude/state/arcs/<slug>.conf to add
# T: prefixes for big files and prune to the 8-12 most important paths.

set -uo pipefail

MODE="dryrun"
case "${1:-}" in
    --apply) MODE="apply" ;;
    --force) MODE="force" ;;
    --help|-h) sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    "") MODE="dryrun" ;;
    *) echo "unknown flag: $1 (use --apply / --force / --help)" >&2; exit 2 ;;
esac

# Note: Claude Code projects directory uses literal username, not ${USER}.
# We discover it dynamically rather than hardcoding.
MEM_DIR=$(ls -d "${HOME}/.claude/projects"/-home-* 2>/dev/null | head -1)/memory
if [[ ! -d "$MEM_DIR" ]]; then
    MEM_DIR="${HOME}/.claude/projects/-home-${USER}/memory"
fi
GRAPH_PROJECTS="${HOME}/ai/global-graph/projects"
ARCS_DIR="${HOME}/.claude/state/arcs"
CMDS_DIR="${HOME}/.claude/commands"
JOURNALS_DIR="${HOME}/ai/global-graph/journals"

mkdir -p "$ARCS_DIR" "$CMDS_DIR"

# slug rules: memory file is project_<slug_underscored>.md, wiki file may use
# dashes. Map underscores → dashes for the wiki lookup.
slug_to_dashed() { echo "$1" | tr '_' '-'; }

found=0
generated=0
skipped=0
shopt -s nullglob
for proj_md in "${MEM_DIR}"/project_*.md; do
    found=$((found + 1))
    base=$(basename "$proj_md" .md)
    slug="${base#project_}"                # e.g. smc_engine
    slug_dashed=$(slug_to_dashed "$slug")  # e.g. my_project → my-project

    wiki_path="${GRAPH_PROJECTS}/${slug_dashed}.md"
    arc_conf="${ARCS_DIR}/${slug}.conf"
    arc_cmd="${CMDS_DIR}/arc-${slug}.md"

    # Skip if no companion wiki page (we only build arcs for projects with
    # both halves so the cluster is meaningful).
    if [[ ! -f "$wiki_path" ]]; then
        continue
    fi

    # Existing-file policy
    if [[ "$MODE" != "force" && ( -f "$arc_conf" || -f "$arc_cmd" ) ]]; then
        skipped=$((skipped + 1))
        if [[ "$MODE" == "dryrun" ]]; then
            printf '  [skip] %-30s (already exists)\n' "$slug"
        fi
        continue
    fi

    # Discover sibling docs/ dir under ~/ai/<slug-dashed>/docs/
    extra_paths=()
    extra_dir="${HOME}/ai/${slug_dashed}/docs"
    if [[ -d "$extra_dir" ]]; then
        while IFS= read -r f; do
            extra_paths+=("$f")
        done < <(ls "$extra_dir"/*.md 2>/dev/null | head -5)
    fi

    # Discover most-recent journal mentioning slug
    recent_journal=""
    if [[ -d "$JOURNALS_DIR" ]]; then
        recent_journal=$(grep -rl --include='*.md' -E "${slug_dashed}|${slug}" "$JOURNALS_DIR" 2>/dev/null \
            | xargs -I{} stat -c '%Y {}' {} 2>/dev/null \
            | sort -rn | head -1 | cut -d' ' -f2-)
    fi

    if [[ "$MODE" == "dryrun" ]]; then
        printf '  [gen]  %-30s wiki=%s mem=%s extras=%d journal=%s\n' \
            "$slug" "$(basename "$wiki_path")" "$(basename "$proj_md")" \
            "${#extra_paths[@]}" "${recent_journal:+$(basename "$recent_journal")}"
        generated=$((generated + 1))
        continue
    fi

    # Write arc config
    {
        echo "# ${slug} arc — auto-generated by build-arc-commands.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# CURATE: add 'T:' prefix to large files for truncation, prune to 8-12 paths."
        echo ""
        echo "# Project nodes"
        echo "$wiki_path"
        echo "T:$proj_md"
        if (( ${#extra_paths[@]} > 0 )); then
            echo ""
            echo "# Companion docs (auto-discovered from ~/ai/${slug_dashed}/docs/)"
            for p in "${extra_paths[@]}"; do
                # Auto-truncate if file > 50KB
                size=$(stat -c%s "$p" 2>/dev/null || stat -f%z "$p" 2>/dev/null || echo 0)
                if (( size > 51200 )); then
                    echo "T:$p"
                else
                    echo "$p"
                fi
            done
        fi
        if [[ -n "$recent_journal" ]]; then
            echo ""
            echo "# Latest session handoff"
            echo "$recent_journal"
        fi
    } > "$arc_conf"

    # Write slash command
    cat > "$arc_cmd" <<EOF
---
description: "Bootstrap a ${slug} arc — load project cluster as cache prefix"
allowed-tools: ["Bash(${HOME}/.claude/state/scripts/arc-bootstrap.sh:*)"]
---

# /arc-${slug} — ${slug} session bootstrap

Loading the ${slug} project cluster (auto-generated). The dump becomes one
user message → captured as cache prefix → 90% discount on subsequent turns.

\`\`\`!
${HOME}/.claude/state/scripts/arc-bootstrap.sh ${slug}
\`\`\`

Now ground yourself in the loaded context. Note the active phase, recent
decisions, and anything in the latest session handoff. Then ask the user
what to work on.

Config: \`~/.claude/state/arcs/${slug}.conf\` — edit to add/remove files
EOF

    generated=$((generated + 1))
    printf '  [gen]  %-30s wrote %s + %s\n' "$slug" "$(basename "$arc_conf")" "$(basename "$arc_cmd")"
done

echo ""
echo "Found project files:    $found"
echo "Eligible (have wiki):   $((generated + skipped))"
echo "Generated this run:     $generated"
echo "Skipped (existing):     $skipped"
if [[ "$MODE" == "dryrun" ]]; then
    echo ""
    echo "(dry run — pass --apply to write files, --force to overwrite existing)"
fi
